"""change server_default in status in Attachment

Revision ID: 88294be23839
Revises: ae6729e2fd27
Create Date: 2026-04-07 16:48:05.747369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88294be23839'
down_revision: Union[str, Sequence[str], None] = 'ae6729e2fd27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Done'::character varying"),
               server_default=sa.text("'Processing'::character varying")
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Processing'::character varying"),
                server_default=sa.text("'Done'::character varying"))
    # ### end Alembic commands ###
