"""Add status for file  PipleLine Handlingg

Revision ID: ae6729e2fd27
Revises: 8ddc5ca05af4
Create Date: 2026-04-07 15:14:44.219892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6729e2fd27'
down_revision: Union[str, Sequence[str], None] = '8ddc5ca05af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', 
                  sa.Column('status', sa.String(), nullable=False, server_default="Done"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'status')
    # ### end Alembic commands ###
